var steve = 39
var glados = 20
var pikachu = 13
var masterChief = 13
var mario = 5
var pacman = 4
var tomNook = 4
var sage = 4
var link = 3
var chung_li = 0
console.log(steve + glados + pikachu + masterChief + mario + pacman + tomNook + sage + link + chung_li)
console.log("First: Steve =" + steve)
console.log("Second: GLaDOS =" + glados)
console.log("Third: Pikachu =" + pikachu)
console.log("Forth: Master Chief =" + masterChief)
console.log("Fifth: Mario =" + mario)
console.log("Sixth: Pacman =" + pacman)
console.log("Seventh: Tom Nook =" + tomNook)
console.log("Eighth: Sage =" + sage)
console.log("Ninth: Link =" + link)
console.log("Tenth: Chung Li =" + chung_li)
